#!/usr/bin/env node
import { Command } from "commander";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { readCase, RunResultSchema, validateCase, type BenchmarkCase } from "../../core/src/index.js";
import { JsonFileAdapter, SingleAgentAdapter, SwarmReviewAdapter } from "../../adapters/src/index.js";
import { scoreRun, terminalSummary, writeReports } from "../../reporter/src/index.js";

const root = resolve(import.meta.dirname, "../../.."); const caseRoot = join(root, "benchmarks", "v0.1");
function cases(): BenchmarkCase[] { return readdirSync(caseRoot, { withFileTypes: true }).filter((item) => item.isDirectory()).map((item) => readCase(join(caseRoot, item.name, "case.json"))); }
function patchFor(benchmarkCase: BenchmarkCase): string { return readFileSync(join(caseRoot, benchmarkCase.repository.patchPath), "utf8"); }
const program = new Command().name("specbench").description("Local-first requirement-adherence benchmark").version("0.1.0");
program.command("validate").description("validate benchmark definitions").action(() => { const errors = cases().flatMap((item) => validateCase(caseRoot, item)); if (errors.length) { console.error(errors.join("\n")); process.exitCode = 1; } else console.log(`Validated ${cases().length} cases (v0.1).`); });
program.command("list").description("list available cases").action(() => cases().forEach((item) => console.log(`${item.id}\t${item.title}`)));
program.command("run").description("run a reviewer and save raw/normalized results").requiredOption("--reviewer <name>", "json-file, swarm-review, or single-agent").option("--input <file>", "local reviewer result JSON").option("--fixture <name>", "use fixtures/<name>.json offline").option("--max-cases <number>", "case limit", "3").option("--max-calls <number>", "model-call limit", "3").option("--max-output-tokens <number>", "per-call output token limit", "1500").option("--max-cost <usd>", "maximum estimated cost").option("--dry-run", "do not call a reviewer").option("--output <file>", "run result path", join(root, "results", "run.json")).action(async (options) => {
  const selected = cases().slice(0, Number(options.maxCases)); if (!Number.isInteger(Number(options.maxCases)) || selected.length > Number(options.maxCalls)) throw new Error("max-cases must be an integer no greater than max-calls"); if (options.dryRun) console.log(`Dry run: ${selected.length} case(s), reviewer ${options.reviewer}, at most ${options.maxCalls} calls.`);
  const input = options.fixture ? join(root, "fixtures", `${options.fixture}.json`) : options.input; if (options.fixture && !existsSync(input)) throw new Error(`Fixture does not exist: ${options.fixture}`);
  const adapter = options.reviewer === "json-file" ? new JsonFileAdapter(required(input, "--input or --fixture is required for json-file")) : options.reviewer === "swarm-review" ? new SwarmReviewAdapter(required(input, "--input or --fixture is required for swarm-review")) : options.reviewer === "single-agent" ? new SingleAgentAdapter() : (() => { throw new Error(`Unknown reviewer: ${options.reviewer}`); })();
  const outputs = []; let totalCost = 0; for (const benchmarkCase of selected) { const output = await adapter.review({ benchmarkVersion: "v0.1", case: benchmarkCase, patch: patchFor(benchmarkCase), dryRun: options.dryRun, maxOutputTokens: Number(options.maxOutputTokens) }); totalCost += output.estimatedCostUsd ?? 0; if (options.maxCost && totalCost > Number(options.maxCost)) throw new Error("Run exceeds --max-cost"); outputs.push({ caseId: benchmarkCase.id, raw: output.raw ?? output, output }); }
  mkdirSync(resolve(options.output, ".."), { recursive: true }); writeFileSync(options.output, `${JSON.stringify({ schemaVersion: "1", benchmarkVersion: "v0.1", reviewer: { name: adapter.name, version: adapter.version }, createdAt: new Date().toISOString(), configuration: { dryRun: Boolean(options.dryRun), maxCalls: Number(options.maxCalls), maxOutputTokens: Number(options.maxOutputTokens) }, cases: outputs }, null, 2)}\n`); console.log(`Saved ${outputs.length} case result(s) to ${options.output}`);
});
program.command("score").description("score a run result").requiredOption("--results <file>", "run result JSON").option("--output <file>", "scored JSON path").action((options) => { const scored = scoreRun(RunResultSchema.parse(JSON.parse(readFileSync(options.results, "utf8"))), cases()); console.log(terminalSummary(scored)); if (options.output) { mkdirSync(resolve(options.output, ".."), { recursive: true }); writeFileSync(options.output, `${JSON.stringify(scored, null, 2)}\n`); } });
program.command("report").description("generate JSON and static HTML reports").requiredOption("--results <file>", "run result JSON").option("--json <file>", "JSON report", join(root, "results", "report.json")).option("--html <file>", "HTML report", join(root, "results", "report.html")).action((options) => { const scored = scoreRun(RunResultSchema.parse(JSON.parse(readFileSync(options.results, "utf8"))), cases()); mkdirSync(resolve(options.json, ".."), { recursive: true }); mkdirSync(resolve(options.html, ".."), { recursive: true }); writeReports(scored, options.json, options.html); console.log(terminalSummary(scored)); console.log(`Wrote ${options.json} and ${options.html}`); });
function required(value: string | undefined, message: string): string { if (!value) throw new Error(message); return value; }
program.parseAsync().catch((error: Error) => { console.error(`specbench: ${error.message}`); process.exitCode = 1; });
