#!/usr/bin/env node
import { Command } from "commander";
import { appendFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { join, resolve } from "node:path";
import { AdjudicationRecordSchema, readCase, ExperimentConfigurationSchema, RunResultSchema, validateCase, type BenchmarkCase } from "../../core/src/index.js";
import { configureLiveBudget, liveBudgetStatus, ControlledSwarmAdapter, JsonFileAdapter, SingleAgentAdapter, SwarmReviewAdapter } from "../../adapters/src/index.js";
import { LiveBudgetLedger } from "../../adapters/src/live-budget-ledger.js";
import { scoreRun, summarizeExperiment, terminalSummary, writeReports } from "../../reporter/src/index.js";

const root = resolve(import.meta.dirname, "../../..");
const smokeLedgerFile = join(root, "results", "v0.3", "live-smoke-test", "budget-ledger.json");
function caseRoot(version: string): string { return join(root, "benchmarks", version); }
function benchmarkCases(version: string): BenchmarkCase[] { const directory = caseRoot(version); if (!existsSync(directory)) throw new Error(`Unknown benchmark version: ${version}`); return readdirSync(directory, { withFileTypes: true }).filter((item) => item.isDirectory() && existsSync(join(directory, item.name, "case.json"))).map((item) => readCase(join(directory, item.name, "case.json"))); }
function patchFor(version: string, benchmarkCase: BenchmarkCase): string { return readFileSync(join(caseRoot(version), benchmarkCase.repository.patchPath), "utf8"); }
const program = new Command().name("specbench").description("Local-first requirement-adherence benchmark").version("0.3.1-beta");
program.command("validate").description("validate benchmark definitions").option("--benchmark <version>", "benchmark version", "v0.2").action((options) => { const rootForVersion = caseRoot(options.benchmark); const selected = benchmarkCases(options.benchmark); const errors = selected.flatMap((item) => validateCase(rootForVersion, item)); if (errors.length) { console.error(errors.join("\n")); process.exitCode = 1; } else console.log(`Validated ${selected.length} cases (${options.benchmark}).`); });
program.command("list").description("list available cases").option("--benchmark <version>", "benchmark version", "v0.2").action((options) => benchmarkCases(options.benchmark).forEach((item) => console.log(`${item.id}\t${item.title}`)));
program.command("smoke-preflight").description("safe local smoke-test preflight; never calls a model").action(() => { const configured = Boolean(process.env.OPENAI_API_KEY); const budget = Number(process.env.SPECBENCH_MAX_TOTAL_COST_USD); if (!configured) throw new Error("OPENAI_API_KEY is missing from shell environment and .env.local"); if (budget !== 1) throw new Error("SPECBENCH_MAX_TOTAL_COST_USD must be exactly 1.00 for this smoke test"); console.log("OPENAI_API_KEY: configured"); console.log("Experiment budget: $1.00"); console.log("Model: gpt-5-nano; pricing: $0.05/M input, $0.40/M output; case: admin-invite-authorization; planned calls: 10; max output tokens: 400"); });
program.command("smoke-budget-init").description("one-time initialize the recorded, secret-free smoke budget ledger").action(() => { const status = new LiveBudgetLedger(smokeLedgerFile).initializeRecordedSmokeSpend(); console.log(`Initialized smoke ledger: measured $${status.measuredUsd.toFixed(6)}`); });
program.command("smoke-budget-status").description("display the local smoke budget ledger without model calls").action(() => { const status = new LiveBudgetLedger(smokeLedgerFile).audit(); console.log(`Ceiling: $${status.ceilingUsd.toFixed(6)}\nMeasured: $${status.measuredUsd.toFixed(6)}\nConservatively committed: $${status.conservativelyCommittedUsd.toFixed(6)}\nOutstanding reservations: $${status.outstandingReservationsUsd.toFixed(6)}\nRemaining: $${status.remainingUsd.toFixed(6)}\nLast update: ${status.updatedAt}`); });
program.command("smoke-budget-audit").description("validate the local smoke budget ledger without model calls").action(() => { const status = new LiveBudgetLedger(smokeLedgerFile).audit(); console.log(`Smoke budget ledger audit passed; remaining $${status.remainingUsd.toFixed(6)}`); });
program.command("live-smoke-one").description("run exactly one durably budgeted smoke configuration").requiredOption("--config <file>", "smoke config filename").action(async (options) => { const ceiling = Number(process.env.SPECBENCH_MAX_TOTAL_COST_USD); if (!process.env.OPENAI_API_KEY || ceiling !== 1) throw new Error("Run via pnpm specbench:local after setting exactly SPECBENCH_MAX_TOTAL_COST_USD=1.00"); const config = ExperimentConfigurationSchema.parse(JSON.parse(readFileSync(join(root, "experiments", "v0.3", options.config), "utf8"))); const benchmarkCase = benchmarkCases("v0.2").find((item) => item.id === "admin-invite-authorization")!; const attemptId = `${config.id}-${randomUUID()}`; configureLiveBudget(smokeLedgerFile, 0.05, 0.40, { runId: attemptId, configurationId: config.id, caseId: benchmarkCase.id }); const adapter = config.reviewerType === "single-agent" ? new SingleAgentAdapter(config.reviewerVersion, config.model) : new ControlledSwarmAdapter(config.debateRounds, config.reviewerVersion, config.model); const startedAt = new Date().toISOString(); let output: any; try { output = await adapter.review({ benchmarkVersion: "v0.2", case: benchmarkCase, patch: patchFor("v0.2", benchmarkCase), maxOutputTokens: 600 }); } catch (error: any) { output = { findings: [], metadata: { failure: error instanceof Error ? error.message : String(error), errorCategory: error?.name ?? "unknown", budget: error?.specbenchBudget ?? null } }; } const budget = liveBudgetStatus(); const record = { schemaVersion: "1", runId: attemptId, createdAt: startedAt, configurationId: config.id, repetition: 1, startedAt, completedAt: new Date().toISOString(), benchmarkVersion: "v0.2", reviewer: { name: adapter.name, version: adapter.version }, configuration: { ...config, maxOutputTokens: 600 }, cases: [{ caseId: benchmarkCase.id, raw: output.raw ?? null, output: { ...output, metadata: { ...output.metadata, attemptId, model: config.model, cumulativeMeasuredCostUsd: budget?.measuredUsd ?? 0, cumulativeCommittedCostUsd: budget?.conservativelyCommittedUsd ?? 0, gitCommit: process.env.GITHUB_SHA ?? "local" } } }] }; const out = join(root, "results", "v0.3", "live-smoke-test"); mkdirSync(out, { recursive: true }); writeFileSync(join(out, `${attemptId}.json`), `${JSON.stringify(record, null, 2)}\n`); console.log(`Attempt ${config.id}: measured $${budget?.measuredUsd.toFixed(6) ?? "0"}; committed $${budget?.conservativelyCommittedUsd.toFixed(6) ?? "0"}; remaining $${budget?.remainingUsd.toFixed(6) ?? "0"}`); });
program.command("live-smoke-test").description("deprecated; use live-smoke-one so each configuration is recorded durably").action(() => { throw new Error("live-smoke-test is disabled; invoke live-smoke-one once per configuration after smoke-budget-status"); });
program.command("run").description("run a reviewer and save raw/normalized results").requiredOption("--reviewer <name>", "json-file, swarm-review, or single-agent").option("--benchmark <version>", "benchmark version", "v0.2").option("--input <file>", "local reviewer result JSON").option("--fixture <name>", "use fixtures/<name>.json offline").option("--max-cases <number>", "case limit", "10").option("--max-calls <number>", "model-call limit", "10").option("--max-output-tokens <number>", "per-call output token limit", "1500").option("--max-cost <usd>", "maximum estimated cost").option("--dry-run", "do not call a reviewer").option("--output <file>", "run result path", join(root, "results", "run.json")).action(async (options) => {
  const versionCases = benchmarkCases(options.benchmark); const selected = versionCases.slice(0, Number(options.maxCases)); if (!Number.isInteger(Number(options.maxCases)) || selected.length > Number(options.maxCalls)) throw new Error("max-cases must be an integer no greater than max-calls"); if (options.dryRun) console.log(`Dry run: ${selected.length} case(s), reviewer ${options.reviewer}, at most ${options.maxCalls} calls.`);
  const input = options.fixture ? join(root, "fixtures", `${options.fixture}.json`) : options.input; if (options.fixture && !existsSync(input)) throw new Error(`Fixture does not exist: ${options.fixture}`);
  const adapter = options.reviewer === "json-file" ? new JsonFileAdapter(required(input, "--input or --fixture is required for json-file")) : options.reviewer === "swarm-review" ? new SwarmReviewAdapter(required(input, "--input or --fixture is required for swarm-review")) : options.reviewer === "single-agent" ? new SingleAgentAdapter() : (() => { throw new Error(`Unknown reviewer: ${options.reviewer}`); })();
  const outputs = []; let totalCost = 0; for (const benchmarkCase of selected) { const output = await adapter.review({ benchmarkVersion: options.benchmark, case: benchmarkCase, patch: patchFor(options.benchmark, benchmarkCase), dryRun: options.dryRun, maxOutputTokens: Number(options.maxOutputTokens) }); totalCost += output.estimatedCostUsd ?? 0; if (options.maxCost && totalCost > Number(options.maxCost)) throw new Error("Run exceeds --max-cost"); outputs.push({ caseId: benchmarkCase.id, raw: output.raw ?? output, output }); }
  mkdirSync(resolve(options.output, ".."), { recursive: true }); writeFileSync(options.output, `${JSON.stringify({ schemaVersion: "1", benchmarkVersion: options.benchmark, reviewer: { name: adapter.name, version: adapter.version }, createdAt: new Date().toISOString(), configuration: { dryRun: Boolean(options.dryRun), maxCalls: Number(options.maxCalls), maxOutputTokens: Number(options.maxOutputTokens), maxCostUsd: options.maxCost ? Number(options.maxCost) : null, benchmarkVersion: options.benchmark }, cases: outputs }, null, 2)}\n`); console.log(`Saved ${outputs.length} case result(s) to ${options.output}`);
});
program.command("score").description("score a run result").requiredOption("--results <file>", "run result JSON").option("--output <file>", "scored JSON path").action((options) => { const run = RunResultSchema.parse(JSON.parse(readFileSync(options.results, "utf8"))); const scored = scoreRun(run, benchmarkCases(run.benchmarkVersion)); console.log(terminalSummary(scored)); if (options.output) { mkdirSync(resolve(options.output, ".."), { recursive: true }); writeFileSync(options.output, `${JSON.stringify(scored, null, 2)}\n`); } });
program.command("report").description("generate JSON and static HTML reports").requiredOption("--results <file>", "run result JSON").option("--json <file>", "JSON report", join(root, "results", "report.json")).option("--html <file>", "HTML report", join(root, "results", "report.html")).action((options) => { const run = RunResultSchema.parse(JSON.parse(readFileSync(options.results, "utf8"))); const scored = scoreRun(run, benchmarkCases(run.benchmarkVersion)); mkdirSync(resolve(options.json, ".."), { recursive: true }); mkdirSync(resolve(options.html, ".."), { recursive: true }); writeReports(scored, options.json, options.html); console.log(terminalSummary(scored)); console.log(`Wrote ${options.json} and ${options.html}`); });
program.command("experiment").description("run one v0.3 configuration (live calls are explicit)").option("--config <file>", "configuration path").option("--all", "run every v0.3 configuration").option("--dry-run", "show plan without model calls").option("--fixture <name>", "offline fixture used for every case").option("--output-dir <dir>", "result directory", join(root, "results", "v0.3", "runs")).action(async (options) => {
  const configs = options.all ? readdirSync(join(root, "experiments", "v0.3")).filter((f) => f.endsWith(".json")).map((f) => join(root, "experiments", "v0.3", f)) : [required(options.config, "--config or --all is required")];
  for (const configPath of configs) { const config = ExperimentConfigurationSchema.parse(JSON.parse(readFileSync(configPath, "utf8"))); const cases = benchmarkCases(config.benchmarkVersion).filter((item) => config.caseIds.includes(item.id));
    const maxPossible = config.maxEstimatedCostUsd; const plannedCalls = cases.length * config.repetitions * (config.reviewerType === "single-agent" ? 1 : config.agentCount + config.debateRounds + 1); console.log(`${config.id}: ${cases.length} cases × ${config.repetitions} repetitions; ${plannedCalls} planned calls (${config.maxCalls} ceiling); ${config.model}; ${config.maxOutputTokens} output tokens/call; maximum cost $${maxPossible.toFixed(2)}.`);
    if (options.dryRun) continue;
    if (!options.fixture && !process.env.OPENAI_API_KEY) throw new Error("OPENAI_API_KEY is required for a live experiment. Use --dry-run or --fixture for offline execution.");
    if (!options.fixture && (!Number.isFinite(Number(process.env.SPECBENCH_INPUT_USD_PER_MILLION)) || !Number.isFinite(Number(process.env.SPECBENCH_OUTPUT_USD_PER_MILLION)))) throw new Error("Live experiments require SPECBENCH_INPUT_USD_PER_MILLION and SPECBENCH_OUTPUT_USD_PER_MILLION so the configured cost ceiling can be enforced.");
    for (let repetition = 1; repetition <= config.repetitions; repetition++) { const runId = `${config.id}-r${repetition}-${randomUUID()}`; const outputPath = join(options.outputDir, `${runId}.json`); if (existsSync(outputPath)) throw new Error(`Refusing to overwrite completed result: ${outputPath}`);
      const adapter = options.fixture ? new JsonFileAdapter(join(root, "fixtures", `${options.fixture}.json`)) : config.reviewerType === "single-agent" ? new SingleAgentAdapter(config.reviewerVersion, config.model) : new ControlledSwarmAdapter(config.debateRounds, config.reviewerVersion, config.model);
      const startedAt = new Date().toISOString(); const outputs: unknown[] = []; let spent = 0;
      for (const benchmarkCase of cases) { const caseStarted = new Date().toISOString(); try { const output = await adapter.review({ benchmarkVersion: config.benchmarkVersion, case: benchmarkCase, patch: patchFor(config.benchmarkVersion, benchmarkCase), maxOutputTokens: config.maxOutputTokens }); if (!options.fixture && output.estimatedCostUsd === undefined) throw new Error("provider usage could not be priced; case retained without continuing live spend"); spent += output.estimatedCostUsd ?? 0; if (spent > config.maxEstimatedCostUsd) throw new Error("configured cost ceiling exceeded"); outputs.push({ caseId: benchmarkCase.id, raw: output.raw ?? output, output: { ...output, metadata: { ...output.metadata, runId, repetition, startedAt: caseStarted, completedAt: new Date().toISOString(), model: config.model, retryCount: 0 } } }); } catch (error) { outputs.push({ caseId: benchmarkCase.id, raw: null, output: { findings: [], metadata: { runId, repetition, startedAt: caseStarted, completedAt: new Date().toISOString(), model: config.model, retryCount: 0, failure: error instanceof Error ? error.message : String(error) } } }); }
      }
      mkdirSync(options.outputDir, { recursive: true }); writeFileSync(outputPath, `${JSON.stringify({ schemaVersion: "1", runId, configurationId: config.id, repetition, startedAt, completedAt: new Date().toISOString(), benchmarkVersion: config.benchmarkVersion, reviewer: { name: adapter.name, version: adapter.version }, createdAt: startedAt, configuration: config, cases: outputs }, null, 2)}\n`); console.log(`Saved ${runId} (${outputs.length} cases) to ${outputPath}`);
    }
  }
});
program.command("experiment-score").description("score all saved v0.3 runs independently").option("--runs <dir>", "run directory", join(root, "results", "v0.3", "runs")).option("--output <file>", "scored output", join(root, "results", "v0.3", "automatic-results.json")).action((options) => { const scored = readdirSync(options.runs, { withFileTypes: true }).filter((f) => f.isFile() && f.name.startsWith("v03-") && f.name.endsWith(".json")).map((f) => scoreRun(RunResultSchema.parse(JSON.parse(readFileSync(join(options.runs, f.name), "utf8"))), benchmarkCases("v0.2"))); mkdirSync(resolve(options.output, ".."), { recursive: true }); writeFileSync(options.output, `${JSON.stringify(scored, null, 2)}\n`); console.log(`Scored ${scored.length} run(s) to ${options.output}`); });
program.command("adjudicate").description("append one independently reviewed classification record").requiredOption("--record <file>", "JSON adjudication record").option("--output <file>", "JSONL ledger", join(root, "results", "v0.3", "adjudications", "records.jsonl")).action((options) => { const record = AdjudicationRecordSchema.parse(JSON.parse(readFileSync(options.record, "utf8"))); mkdirSync(resolve(options.output, ".."), { recursive: true }); appendFileSync(options.output, `${JSON.stringify(record)}\n`); console.log(`Appended adjudication for ${record.caseId} / ${record.runId}`); });
program.command("experiment-report").description("generate v0.3 report artifacts from saved scores").option("--scores <file>", "automatic score file", join(root, "results", "v0.3", "automatic-results.json")).option("--output-dir <dir>", "report directory", join(root, "results", "v0.3")).action((options) => { const scores = JSON.parse(readFileSync(options.scores, "utf8")); mkdirSync(options.outputDir, { recursive: true }); writeFileSync(join(options.outputDir, "summary.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), preliminary: true, runs: scores }, null, 2)}\n`); const rows = ["configurationId,repetition,truePositives,falsePositives,falseNegatives,precision,recall,f1,runtimeMs,estimatedCostUsd", ...scores.map((s: any) => [s.run.configuration.id, s.run.repetition ?? "", s.metrics.truePositives, s.metrics.falsePositives, s.metrics.falseNegatives, s.metrics.precision ?? "", s.metrics.recall ?? "", s.metrics.f1 ?? "", s.metrics.runtimeMs, s.metrics.estimatedCostUsd].join(","))]; writeFileSync(join(options.outputDir, "aggregate.csv"), `${rows.join("\n")}\n`); writeFileSync(join(root, "docs", "V0.3_RESULTS.md"), `# SpecBench v0.3 results\n\n## Status\n\nPreliminary: generated from saved artifacts; no claim is made until all configurations have complete repetitions and human adjudication.\n\n## Research question\n\nDoes multi-agent debate improve detection of explicit product-requirement violations enough to justify cost, latency, and false positives?\n\n## Limitations\n\nThis is a 10-case controlled benchmark from one reference SaaS environment, created by the same team as its evaluator. Results may be sensitive to prompts, models, randomness, and matching rules; three repetitions remain a small sample. It measures requirement-violation detection, not general code-review quality. Interpret comparisons as directional, not universal.\n\n## Reproduction\n\nRun \`pnpm experiment:v0.3:dry-run\`, then the three explicit configuration commands, \`pnpm experiment:v0.3:score\`, and \`pnpm experiment:v0.3:report\`. Raw run files are retained under \`results/v0.3/runs/\`.\n`); console.log(`Wrote JSON/CSV and docs/V0.3_RESULTS.md`); });
program.command("experiment-report-v03").description("generate complete static v0.3 artifacts from saved scores").option("--scores <file>", "automatic score file", join(root, "results", "v0.3", "automatic-results.json")).option("--output-dir <dir>", "report directory", join(root, "results", "v0.3")).action((options) => { const runs = JSON.parse(readFileSync(options.scores, "utf8")); const summaries = summarizeExperiment(runs); const charts = join(options.outputDir, "charts"); mkdirSync(charts, { recursive: true });
  writeFileSync(join(options.outputDir, "summary.json"), `${JSON.stringify({ schemaVersion: "1", generatedAt: new Date().toISOString(), status: "preliminary", automatic: summaries, humanAdjudicated: null, rawArtifactIndex: runs.map((run: any) => run.run.runId ?? run.run.createdAt) }, null, 2)}\n`);
  const columns = ["truePositives", "falsePositives", "falseNegatives", "precision", "recall", "f1", "severityWeightedRecall", "criticalIssueDetectionRate", "casesWithAllExpectedFindings", "casesWithZeroValidFindings", "averageFindingsPerCase", "runtimeMs", "runtimePerCase", "estimatedCostUsd", "costPerCase", "costPerTruePositive"]; const aggregate = ["configurationId,repetitions,metric,mean,median,min,max,standardDeviation", ...summaries.flatMap((summary) => columns.map((metric) => { const value = summary.automatic[metric]; return [summary.configurationId, summary.repetitions, metric, value.mean ?? "", value.median ?? "", value.min ?? "", value.max ?? "", value.standardDeviation ?? ""].join(","); }))]; writeFileSync(join(options.outputDir, "aggregate.csv"), `${aggregate.join("\n")}\n`);
  const perCase = ["configurationId,repetition,caseId,truePositives,falsePositives,falseNegatives,runtimeMs,estimatedCostUsd", ...summaries.flatMap((summary) => summary.perCase.map((row) => [summary.configurationId, row.repetition, row.caseId, row.truePositives, row.falsePositives, row.falseNegatives, row.runtimeMs, row.estimatedCostUsd].join(",")))]; writeFileSync(join(options.outputDir, "per-case.csv"), `${perCase.join("\n")}\n`);
  for (const metric of ["precision", "recall", "f1", "severityWeightedRecall", "criticalIssueDetectionRate", "costPerCase", "costPerTruePositive", "runtimePerCase", "falsePositives"]) { const labels = summaries.map((summary) => `${summary.configurationId}: ${(summary.automatic[metric]?.mean ?? 0).toFixed(3)}`); writeFileSync(join(charts, `${metric}.svg`), `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="${80 + labels.length * 30}"><style>text{font:16px sans-serif}</style><text x="20" y="30">${metric} (mean, generated from saved results)</text>${labels.map((label, index) => `<text x="20" y="${65 + index * 28}">${label}</text>`).join("")}</svg>`); }
  const matrixRows = summaries.flatMap((summary) => summary.perCase.map((row) => `${summary.configurationId},${row.repetition},${row.caseId},${row.truePositives > 0 ? "detected" : "missed"}`)); writeFileSync(join(charts, "per-case-detection-matrix.csv"), `configurationId,repetition,caseId,detection\n${matrixRows.join("\n")}\n`);
  const html = `<!doctype html><meta charset="utf-8"><title>SpecBench v0.3 results</title><style>body{font:16px system-ui;max-width:1100px;margin:2rem auto}table{border-collapse:collapse}td,th{border:1px solid #ddd;padding:.4rem;text-align:left}</style><h1>SpecBench v0.3 results</h1><p><strong>Preliminary.</strong> Automatic results are retained separately from human adjudication.</p><table><tr><th>Configuration</th><th>Runs</th><th>Precision</th><th>Recall</th><th>F1</th><th>Cost</th><th>Runtime ms</th></tr>${summaries.map((summary) => `<tr><td>${summary.configurationId}</td><td>${summary.repetitions}</td><td>${summary.automatic.precision.mean ?? "n/a"}</td><td>${summary.automatic.recall.mean ?? "n/a"}</td><td>${summary.automatic.f1.mean ?? "n/a"}</td><td>${summary.automatic.estimatedCostUsd.mean ?? "n/a"}</td><td>${summary.automatic.runtimeMs.mean ?? "n/a"}</td></tr>`).join("")}</table><h2>Limitations</h2><p>Ten controlled cases from one reference SaaS, created by the same team as the evaluator. Results are sensitive to prompts, models, randomness, and matching rules. Three repetitions are a small sample; this measures requirement-violation detection, not general code-review quality. Interpret results as directional, not universal.</p>`; writeFileSync(join(options.outputDir, "report.html"), html); console.log(`Wrote v0.3 JSON, CSV, HTML, and SVG charts to ${options.outputDir}`); });
function required(value: string | undefined, message: string): string { if (!value) throw new Error(message); return value; }
program.parseAsync().catch((error: Error) => { console.error(`specbench: ${error.message}`); process.exitCode = 1; });
